# PyTorch

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

在本堂課中，我們會學習 PyTorch。PyTorch 是一個用來構建動態類神經網路的機器學習框架。我們會學習基本的部分，比如說建立和使用 tensors，等到下一堂課時，才會學習透過 PyTorch 來建立模型。

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/pytorch.png" width=300>

# Tensor 基礎

In [1]:
# 安裝 PyTorch
!pip3 install torch

You are using pip version 8.1.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np
import torch

In [3]:
# 建立一個 tensor
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00, -4.6566e-10],
        [ 4.2039e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  9.3174e-39,  2.7837e-40]])


In [7]:
# 建立一個隨機的 tensor
x = torch.randn(2, 3) # 常態分佈 (rand(2,3) -> 均勻分佈)
print (x)

tensor([[ 1.3104, -1.6026,  1.4813],
        [ 0.6529,  0.9398, -0.7048]])


In [6]:
# 建立 0 和 1 的 tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
# NumPy 陣列 → Tensor
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.0372, 0.6757, 0.9554],
        [0.5651, 0.2336, 0.8303]], dtype=torch.float64)


In [9]:
# 改變 tensor 型別
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor 操作

In [10]:
# 相加
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.5650, -0.0173,  1.1263],
        [ 3.4274,  1.3610, -0.9262]])


In [11]:
# 內積操作
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[ 1.3294, -2.4559],
        [-0.4337,  4.9667]])


In [12]:
# 轉置
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0257, -0.5716, -0.9207],
        [-1.0590,  0.2942, -0.7114]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.0257, -1.0590],
        [-0.5716,  0.2942],
        [-0.9207, -0.7114]])


In [13]:
# 改變 tensor 形狀 (reshape)
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.0257, -0.5716],
        [-0.9207, -1.0590],
        [ 0.2942, -0.7114]])


In [8]:
# reshape 危險之處 (意想不到的後果)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape)) 
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape)) 
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [9]:
# 維度操作
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # 將每列的值相加到行
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # 將每行的值相加到列
print("Values: \n{}".format(z))

Values: 
tensor([[-0.3397, -2.0628, -1.3581],
        [-1.4550,  0.6226, -0.2950]])
Values: 
tensor([-1.7947, -1.4402, -1.6531])
Values: 
tensor([-3.7607, -1.1273])


# 索引、分片和取交集

In [10]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[-1.6521,  0.1625, -0.1273, -0.8788],
        [-0.3718, -1.3267,  0.1469,  1.3535],
        [ 1.1699,  1.4596,  0.0647,  1.3155]])
x[:1]: 
tensor([[-1.6521,  0.1625, -0.1273, -0.8788]])
x[:1, 1:3]: 
tensor([[ 0.1625, -0.1273]])


In [11]:
# 透過維度的索引來選取資料
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # 第 0 和第 2 行
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # 選取 (0, 0) & (2, 1) 的值
print("Values: \n{}".format(chosen)) 

Values: 
tensor([[ 0.2905,  0.7733, -0.6307],
        [-0.5074, -0.6933, -1.2160]])
Values: 
tensor([[ 0.2905, -0.6307],
        [-0.5074, -1.2160]])
Values: 
tensor([ 0.2905, -1.2160])


In [18]:
# 相加
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # 以列的維度進行疊合 (dim=1 則是以行來進行疊合)
print("Values: \n{}".format(y))

Values: 
tensor([[-0.8443,  0.9883,  2.2796],
        [-0.0482, -0.1147, -0.5290]])
Values: 
tensor([[-0.8443,  0.9883,  2.2796],
        [-0.0482, -0.1147, -0.5290],
        [-0.8443,  0.9883,  2.2796],
        [-0.0482, -0.1147, -0.5290]])


# 梯度

In [12]:
# Tensors 的梯度操作
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z 必須要是純量
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.5930, 0.4767, 0.1042, 0.8997],
        [0.2205, 0.9542, 0.8748, 0.9583],
        [0.3877, 0.1511, 0.9198, 0.8792]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(y)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA tensors

In [13]:
# 確認 CUDA 是否可用
print (torch.cuda.is_available())

False


如果上面的結果是 False，到 `Runtime` → `Change runtime type` 中，在 `Hardware accelerator` 底下選擇 `GPU`

In [14]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [15]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

AssertionError: Torch not compiled with CUDA enabled